apiVersion: apps/v1
kind: Deployment
metadata:
  name: syed-app
  labels:
    app: syed-app
spec:
  replicas: 15
  selector:
    matchLabels:
      app: syed-app
  template:
    metadata:
      labels:
        app: syed-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: syed-app
        #image: veeranarni/hotstar:latest
        image: 681117450266.dkr.ecr.us-east-1.amazonaws.com/port:latest
        imagePullPolicy: "Always"
        
